### ISSUE TITLE
No module named RPi

### ISSUE THREAD

**Issue by VanQz** [osrts/osrts-raspberry#2]
I installed all needed modules as stated and tried to run program

[root@localhost osrts-raspberry]# python3.6 program.py -f -n 2
Traceback (most recent call last):
  File "program.py", line 24, in <module>
    from sender import DataSender
  File "/home/osrts-raspberry/sender.py", line 12, in <module>
    from led_controller import LedController
  File "/home/osrts-raspberry/led_controller.py", line 6, in <module>
    import RPi.GPIO as GPIO
ModuleNotFoundError: No module named 'RPi'

**Comment by GuillaumeDeconinck** [comment]
Are your launching it on a Raspberry PI ?
If yes, maybe the package is missing, try `pip3 install RPi.GPIO`

**Comment by VanQz** [comment]
I'm running from centos7.3 in VM. 

Understanding the logic first

**Comment by GuillaumeDeconinck** [comment]
I see.
Then I'm afraid you won't be able to launch it :/
It requires the RPi packages to run, maybe in the future we will make it
optional (or you can try of course, it's led_controller.py that uses the
RPI packages).

**Comment by VanQz** [comment]
I have commented out all the lines related to the led controller and i received this error

[root@localhost osrts-raspberry]# python3.6 program.py -f -n 2
***Option : Fake Reader
Init FileManager
Init FakeTagReader

                           Checkpoint manager                           

 Configuration:                                Status: 
Traceback (most recent call last):
  File "program.py", line 179, in <module>
    show_textual_output()
  File "program.py", line 129, in show_textual_output
    num_str = str(MODEL.get_value('config')['Checkpoint']['num'])
  File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Checkpoint'
